### ISSUE TITLE
Image ubuntu/jammy/cloud cloud-init failed

### ISSUE THREAD

**Issue by subnet-dev** [lxc/lxc-ci#693] opened 2023-01-11 19:22 UTC
To reproduce the issue :

`example.yaml`
```bash
config:
  cloud-init.user-data: |
    #cloud-config
    runcmd:
      - touch /root/cloud.init.ran
```

```bash
lxc image copy images:ubuntu/jammy/cloud local: --vm --copy-aliases --auto-update

lxc image ls
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+
|            ALIAS            | FINGERPRINT  | PUBLIC |             DESCRIPTION             | ARCHITECTURE |      TYPE       |   SIZE   |         UPLOAD DATE          |
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+
| ubuntu/jammy/cloud (3 more) | eef7ae7ff1d2 | no     | Ubuntu jammy amd64 (20230106_09:09) | x86_64       | VIRTUAL-MACHINE | 278.27MB | Jan 11, 2023 at 7:04pm (UTC) |
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+

lxc launch ubuntu/jammy/cloud example --vm < example.yaml

lxc shell example -- cat /var/log/cloud-init.log | head -100
```

cloud-init error message :
```
2023-01-11 19:06:29,047 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceLXD.DataSourceLXD'>
2023-01-11 19:06:29,048 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-01-11 19:06:29,180 - DataSourceLXD.py[DEBUG]: [GET] [HTTP:500] http://lxd/1.0/meta-data
2023-01-11 19:06:29,180 - util.py[DEBUG]: Crawl of metadata service took 0.133 seconds
2023-01-11 19:06:29,181 - handlers.py[DEBUG]: finish: init-local/search-LXD: FAIL: no local data found from DataSourceLXD
2023-01-11 19:06:29,181 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceLXD.DataSourceLXD'> failed
2023-01-11 19:06:29,181 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceLXD.DataSourceLXD'> failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 946, in find_source
    if s.update_metadata_if_supported(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 828, in update_metadata_if_supported
    result = self.get_data()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 373, in get_data
    return_value = self._get_data()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line 193, in _get_data
    self._crawled_metadata = util.log_time(
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2680, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line 428, in read_metadata
    return _MetaDataReader(api_version=api_version)(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line 384, in __call__
    md["meta-data"] = _do_request(session, md_route).text
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceLXD.py", line 297, in _do_request
    raise sources.InvalidMetaDataException(
cloudinit.sources.InvalidMetaDataException: Invalid HTTP response [500] from http://lxd/1.0/meta-data: internal server error

2023-01-11 19:06:29,219 - main.py[DEBUG]: No local datasource found
2023-01-11 19:06:29,219 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-01-11 19:06:29,219 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-01-11 19:06:29,220 - util.py[DEBUG]: Reading from /sys/class/net/enp5s0/address (quiet=False)
2023-01-11 19:06:29,220 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp5s0/address
```

Proof that cloud-init did not work
```bash
lxc shell example -- cat /root/cloud.init.ran

cat: /root/cloud.init.ran: No such file or directory
```

Versions used :
|   | Version  |
|---|---|
| lxc |5.9|
|lxd|5.9|

Host OS
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

I think it would be a good idea to add a check for cloud images by launching the creation of a file with cloud-init and checking that the file has been created.

**Comment by tomponline** [comment] 2023-01-11 19:26
@monstermunchkin can you take this one? Perhaps an issue with lxd-agent providing the devlxd socket?

**Comment by subnet-dev** [comment] 2023-01-11 19:32
I forgot to mention that exactly the same procedure with the ubuntu/focal/cloud image works perfectly. So I think the problem does not come from lxc/lxc but from the image.

**Comment by stgraber** [comment] 2023-01-11 20:36
```
cloudinit.sources.InvalidMetaDataException: Invalid HTTP response [500] from http://lxd/1.0/meta-data: internal server error
```

So could be a lxd-agent problem or LXD on the host not responding or something?

**Comment by subnet-dev** [comment] 2023-01-11 22:11
It looks like cloud ini doesn't have the same data source list.

- [ubuntu-focal-cloud-cloud-init-3ab42ad7c3d2.log](https://github.com/lxc/lxc-ci/files/10396294/ubuntu-focal-cloud-cloud-init.log)
- [ubuntu-jammy-cloud-cloud-init-eef7ae7ff1d2.log](https://github.com/lxc/lxc-ci/files/10396295/ubuntu-jammy-cloud-cloud-init.log)

**Comment by monstermunchkin** [comment] 2023-01-13 11:13
I cannot reproduce this even after multiple tries. So it doesn't seem to be a lxd-agent problem.

**Comment by subnet-dev** [comment] 2023-01-20 15:53
The problem is solved with this image on the exact same server :

```
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+
|            ALIAS            | FINGERPRINT  | PUBLIC |             DESCRIPTION             | ARCHITECTURE |      TYPE       |   SIZE   |         UPLOAD DATE          |
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+
| ubuntu/jammy/cloud (3 more) | 19e1e50e1d27 | no     | Ubuntu jammy amd64 (20230120_07:43) | x86_64       | VIRTUAL-MACHINE | 278.46MB | Jan 20, 2023 at 3:49pm (UTC) |
+-----------------------------+--------------+--------+-------------------------------------+--------------+-----------------+----------+------------------------------+
```

```
cat: -l: No such file or directory
2023-01-20 15:49:50,876 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'init-local' at Fri, 20 Jan 2023 15:49:50 +0000. Up 3.23 seconds.
2023-01-20 15:49:50,876 - main.py[DEBUG]: No kernel command line url found.
2023-01-20 15:49:50,876 - main.py[DEBUG]: Closing stdin.
2023-01-20 15:49:50,894 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2023-01-20 15:49:50,894 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4
2023-01-20 15:49:50,894 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2023-01-20 15:49:50,895 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2023-01-20 15:49:50,895 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2023-01-20 15:49:50,895 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-01-20 15:49:50,895 - stages.py[DEBUG]: no cache found
2023-01-20 15:49:50,895 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2023-01-20 15:49:50,895 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-01-20 15:49:50,981 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-01-20 15:49:50,982 - __init__.py[DEBUG]: Looking for data source in: ['LXD', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2023-01-20 15:49:50,985 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceLXD']
2023-01-20 15:49:50,985 - handlers.py[DEBUG]: start: init-local/search-LXD: searching for local data from DataSourceLXD
2023-01-20 15:49:50,985 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceLXD.DataSourceLXD'>
2023-01-20 15:49:50,985 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-01-20 15:49:51,035 - DataSourceLXD.py[DEBUG]: [GET] [HTTP:200] http://lxd/1.0/meta-data
2023-01-20 15:49:51,061 - DataSourceLXD.py[DEBUG]: [GET] [HTTP:200] http://lxd/1.0/config
2023-01-20 15:49:51,097 - DataSourceLXD.py[DEBUG]: [GET] [HTTP:200] http://lxd/1.0/config/cloud-init.user-data
2023-01-20 15:49:51,119 - DataSourceLXD.py[DEBUG]: [GET] [HTTP:200] http://lxd/1.0/devices
2023-01-20 15:49:51,119 - util.py[DEBUG]: Crawl of metadata service took 0.134 seconds
2023-01-20 15:49:51,119 - util.py[DEBUG]: Attempting to load yaml from string of length 88 with allowed root types (<class 'dict'>,)
2023-01-20 15:49:51,120 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-lxd - wb: [644] 4 bytes
2023-01-20 15:49:51,121 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-lxd'
2023-01-20 15:49:51,121 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpx3w7lhcy) - w: [600] 5172 bytes/chars
```

**Comment by monstermunchkin** [comment] 2023-01-23 13:30
I'm glad the issue fixed itself. Closing this then.

**Closed by monstermunchkin** 2023-01-23 13:30 UTC
